version = 1

[[analyzers]]
enabled = true
name = "test-coverage"

[[analyzers]]
enabled = true
name = "secrets"

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[transformers]]
enabled = true
name = "black"
