default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
    -   id: ruff

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
        args: [--assume-in-merge]
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
    -   id: trailing-whitespace

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks.
    autofix_prs: true
    autoupdate_branch: master
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    submodules: false
