[tool.docformatter]
blank = true
in-place = true
make-summary-multi-line = true
pre-summary-newline = true
recursive = true

[tool.ruff]
fix = true
line-length = 99
output-format = "full"
respect-gitignore = true
target-version = "py312"
lint.dummy-variable-rgx = "^_$"
lint.ignore = ["E501", "E402", "F405", "F403", "B005", "ISC001"]
lint.ignore-init-module-imports = true
lint.select = [
  "B",
  "BLE",
  "C4",
  "E",
  "EXE",
  "F",
  "FA",
  "G",
  "FLY",
  "I",
  "ICN",
  "INP",
  "ISC",
  "PGH",
  "PIE",
  "SIM",
  "T10",
  "T20",
  "TCH",
  "TID",
  "UP",
  "W",
  "YTT"
]
lint.isort.combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
