[tool.black]
line-length = 99
target-version = ['py310']

[tool.docformatter]
blank = true
in-place = true
make-summary-multi-line = true
pre-summary-newline = true
recursive = true

[tool.ruff]
dummy-variable-rgx = "^_$"
fix = true
ignore = ["E501", "E402", "F405", "F403"]
ignore-init-module-imports = true
line-length = 99
respect-gitignore = true
show-source = true
target-version = "py311"

[tool.ruff.isort]
combine-as-imports = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
