[tool.black]
line-length = 99
target-version = ['py39']

[tool.docformatter]
in-place = true
recursive = true
blank = true
pre-summary-newline = true
make-summary-multi-line = true

[tool.ruff]
line-length = 99
target-version = "py39"
fix = true
ignore = ["E501"]
ignore-init-module-imports = true
respect-gitignore = true
dummy-variable-rgx = "^_$"
show-source = true

[tool.ruff.isort]
combine-as-imports = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
