name: Auto Merge

on:
    pull_request_target:
        types: [opened, reopened]

jobs:
    auto-approve:
        runs-on: ubuntu-latest
        steps:
        -   uses: pascalgn/automerge-action@v0.15.5
            if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]' || github.actor == 'github-actions[bot]' }}
            with:
                github-token: ${{secrets.GITHUB_TOKEN}}
